# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 'sritest'
steps:
# Java tool installer v0
# Acquire a specific version of Java from a user-supplied Azure blob or the tool cache and sets JAVA_HOME.


# - task: JavaToolInstaller@0
#   inputs:
#     versionSpec: '11.0.19'
#     jdkArchitectureOption: 'x64'
#     jdkSourceOption: 'PreInstalled'


- task: Gradle@3
  inputs:
    artifactoryConnection: 'test'
    workingDirectory: '/root/myagent/_work/1/s/'
    gradleWrapperFile: 'gradle-examples/gradle-example/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    #jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
    artifactoryResolverService: 'test'
    sourceRepo: 'sri-dines-gradle-dev'
    artifactoryDeployerService: 'test'
    targetRepo: 'sri-dines-gradle-dev'
    usesPlugin: true
    useWrapper: true
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogPublishBuildInfo@1
  name: publishBInfo
  displayName: 'Publish Build Info to JFrog'
  condition: succeeded()
  inputs:
      artifactoryConnection: 'test'
      collectBuildInfo: true
      includeEnvVars: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      
