# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 'sritest'
steps:
# Java tool installer v0
# Acquire a specific version of Java from a user-supplied Azure blob or the tool cache and sets JAVA_HOME.
# - task: JavaToolInstaller@0
#   inputs:
#     versionSpec: '11'
#     jdkArchitectureOption: 'x64'
#     jdkSourceOption: 'PreInstalled'
- task: Bash@3
  displayName: 'Workaround: Set environment variables manually'
  inputs:
    targetType: 'inline'
    script: |
      cd ~
        echo "##vso[task.setvariable variable=HOME]$(pwd)"
        echo "##vso[task.setvariable variable=USER]$(whoami)"
        echo "##vso[task.setvariable variable=JAVA_HOME_11_X64]/usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.el7_9.x86_64/bin/java"
        

- task: Gradle@2
  inputs:
    artifactoryConnection: 'test'
    workingDirectory: '/root/myagent/_work/1/s/'
    gradleWrapperFile: 'gradle-examples/gradle-example/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
    artifactoryResolverService: 'test'
    sourceRepo: 'sri-dines-gradle-dev' 
    artifactoryDeployerService: 'test'
    targetRepo: 'sri-dines-gradle-dev'
    usesPlugin: true
    useWrapper: true
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'


# - task: JFrogGradle@1
#   inputs:
#     gradleBuildFile: 'build.gradle'
#     workDir: '/root/myagent/_work/1/s/'
#     #options: 'gradle-examples/gradle-example/gradlew'
#     gradleWrapperFile: 'gradle-examples/gradle-example/gradlew'
#     tasks: 'artifactoryPublish'
#     artifactoryResolverService: 'test'
#     sourceRepo: 'sri-dines-gradle-dev'
#     artifactoryDeployerService: 'test'
#     targetRepo: 'sri-dines-gradle-dev'
#     usesPlugin: true
#     useWrapper: true
#     collectBuildInfo: true
#     buildName: '$(Build.DefinitionName)'
#     buildNumber: '$(Build.BuildNumber)'

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'test'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

