# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - master
  paths:
    include:
      - gradle-examples/gradle-android-example/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'export JFROG_CLI_LOG_LEVEL=DEBUG'
- task: JFrogGradle@1
  inputs:
    gradleBuildFile: './build.gradle'
    tasks: ' artifactoryPublish'
    artifactoryResolverService: 'arti'
    sourceRepo: 'sri-android-gradle-dev'
    artifactoryDeployerService: 'arti'
    targetRepo: 'sri-android-gradle-dev'
    useWrapper: true
    deployMavenDesc: false
    deployIvyDesc: false
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'arti'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
