trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:
- task: JFrogGradle@1
  inputs:
    gradleBuildFile: 'gradle-examples/gradle-android-library-example-ci-server/build.gradle'
    gradleWrapperFile: 'gradle-examples/gradle-android-library-example-ci-server/gradlew'
    workDir: 'gradle-examples/gradle-android-library-example-ci-server'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'arti'
    sourceRepo: 'sri-dines-gradle-dev'
    artifactoryDeployerService: 'arti'
    targetRepo: 'sri-dines-gradle-dev'
    usesPlugin: true
    useWrapper: true
    deployIvyDesc: false
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'arti'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

# - task: JFrogGradle@1
#   inputs:
#     gradleBuildFile: 'build.gradle'
#     tasks: 'artifactoryPublish'
#     artifactoryResolverService: 'arti'
#     sourceRepo: 'sri-dines-gradle-dev'
#     artifactoryDeployerService: 'arti'
#     targetRepo: 'sri-dines-gradle-dev'
#     useWrapper: true
#     deployMavenDesc: false
#     deployIvyDesc: false
#     collectBuildInfo: true
#     buildName: '$(Build.DefinitionName)'
#     buildNumber: '$(Build.BuildNumber)'